### ISSUE TITLE
Direkte URL zur ILI-Datei

### ISSUE THREAD

**Issue by KunoEpper** [GeoWerkstatt/interlis-model-browser#103]
Mit Klick auf den Modell-Namen gelangt man auf eine Zwischenseite. Auf dieser ist die Modell-Vorschau aufgeführt.
Ich fände es benutzerfreundlich, wenn man direkt auf die Modelldatei springen würde.

**Comment by olivergrimm** [comment]
allenfalls könnten wir hinter dem Modellnamen ein Link-Symbol ergänzen, welches den direkten Sprung zur ILI-Datei ermöglicht.

**Comment by olivergrimm** [comment]
Teil 'Datei' der Suchresultate als Link ausprägen
