### ISSUE TITLE
Suchresultate mit URL versehen

### ISSUE THREAD

**Issue by KunoEpper** [GeoWerkstatt/interlis-model-browser#105]
Die Suchresultate führen bei "Herausgeber" und "Datei" zwei Werte, die als URL bzw. als Link angegeben werden könnten. So gelangt der Benutzer, die Benutzerin direkt zu den Seiten bzw. zum Modell.

**Comment by olivergrimm** [comment]
Herausgeber kann auch Text sein, daher da kein Link.
Modell-Datei wird mit Symbol und Link ergänzt (anstelle des aktuellen Links "Modell-URL")

**Comment by MiraGeowerkstatt** [comment]
Siehe #103
