### ISSUE TITLE
Filterkategorien sind voneinander abhängig

### ISSUE THREAD

**Issue by KunoEpper** [GeoWerkstatt/interlis-model-browser#108]
Die Filerkategorien

- Modellablagen
- Herausgeber
- Schemasprache

sind voneinander abhängig. Über die Darstellung im GUI ist diese Abhängigkeit nicht ersichtlich.
Möchte ich z.B. alle Modelle der Modellablage "models.geo.sz.ch" anzeigen, erhalte ich keine Resultate, wenn die anderen beiden Filtergruppen leer sind.

Damit kann ich folgende Frage nicht beantworten: "Liste mir alle Modelle von 'models.geo.sz.ch' auf, die in 'INTERLIS 2.4' modelliert sind" (falls der Herausgeber leer ist).

Ich meine, wenn eine der Filterkategorien leer ist, sollte diese NICHT berücksichtigt werden.

**Comment by olivergrimm** [comment]
#116

**Comment by olivergrimm** [comment]
Das entspricht der Arbeitsweise und Logik des aktuell implementierten Filters.
