### ISSUE TITLE
Suche nach "nutzungsplanung_catalogue_ch_v1_2_20210901" nicht vollständig

### ISSUE THREAD

**Issue by KunoEpper** [GeoWerkstatt/interlis-model-browser#109]
Bei der Suche nach dem Katalog "nutzungsplanung_catalogue_ch_v1_2_20210901" wird nur das italienische und französische Modell im Suchresultat angezeigt. Das deutsche Modell fehlt. Dieses wird unter "Referenzierte Modelle" aufgeführt.

**Comment by olivergrimm** [comment]
Das italienische und französische Nutzungsplanungs-Modell werden aufgrund der Links zum Katalog gefunden. Beim deutschen Modell fehlt die Katalogzuweisung [https://ilimodels.ch/detail/9cc2ecbecd22600e1e82c3a5116448fb/Nutzungsplanung_V1_2](https://ilimodels.ch/detail/9cc2ecbecd22600e1e82c3a5116448fb/Nutzungsplanung_V1_2)

**Comment by olivergrimm** [comment]
Grund eruieren und kommentieren, wieso das deutsche Modell keinen Katalog zugewiesen hat.

**Comment by patrickackermann** [comment]
Die Referenzierten Modelle eines Katalogs werden aus den _categories_ aus dem ilidata.xml File gelesen. Beim Katalog _nutzungsplanung_catalogue_ch_v1_2_20210901_ ist dort nur das französische und italienische Modell aufgeführt, daher wird das deutsche Modell nicht gefunden.

Im [models.geo.admin.ch/ilidata.xml](https://models.geo.admin.ch/ilidata.xml) hat es einen _basket_ Tag mit Basket Metadaten, der unter anderem auch den deutschen Modelllink _Nutzungsplanung_V1_2.Catalogue_CH_ enthält. In https://usabilityhub.opengis.ch/services/konzept/ wird dieser Tag aber nicht erwähnt und uns ist daher nicht klar, ob sich dieser Tag eignet um den Link zwischen Modell und Katalog herzustellen.

Relevante Stelle aus dem ilidata.xml [models.geo.admin.ch/ilidata.xml](https://models.geo.admin.ch/ilidata.xml):
``` xml
<DatasetIdx16.DataIndex.DatasetMetadata TID="120">
    <id>ch.admin.geo.models.Nutzungsplanung_Catalogue_CH_V1_2_20210901</id>
...
    <categories>
        <DatasetIdx16.Code_>
            <value>http://codes.interlis.ch/type/referenceData</value>
        </DatasetIdx16.Code_>
        <DatasetIdx16.Code_>
            <value>http://codes.interlis.ch/model/PlansDAffectation_V1_2</value>
        </DatasetIdx16.Code_>
        <DatasetIdx16.Code_>
            <value>http://codes.interlis.ch/model/PianiDiUtilizzazione_V1_2</value>
        </DatasetIdx16.Code_>
    </categories>
...
    <baskets>
        <DatasetIdx16.DataIndex.BasketMetadata>
            <id>ch.admin.are.nutzungsplanung_catalogue_ch_v1_2_20210901</id>
            <version>2021-09-01</version>
            <model>
                <DatasetIdx16.ModelLink>
                    <name>Nutzungsplanung_V1_2.Catalogue_CH</name>
                </DatasetIdx16.ModelLink>
            </model>
            <owner>mailto:models@geo.admin.ch</owner>
        </DatasetIdx16.DataIndex.BasketMetadata>
    </baskets>
</DatasetIdx16.DataIndex.DatasetMetadata>
```
