### ISSUE TITLE
Fehlermeldung "Ungültige Modell-URL"

### ISSUE THREAD

**Issue by KunoEpper** [GeoWerkstatt/interlis-model-browser#110]
Gestern hatte ich einen Fehler in die Datei http://models.geo.sz.ch/ilimodels.xml eingebaut. DerEintrag für das Modell "SZ_Basis_V1_0" habe ich zweimal aufgeführt.
Die heutige Suche nach "SZ_Basis_V1_0" liefert korrekt zwei Einträge.

![grafik](https://user-images.githubusercontent.com/6049956/191421779-139a7307-48d2-4f54-bedb-6a7f4f586d77.png)

Beim Aufrufen der Detail-Info (Klick auf den Modell-Namen) erscheint hingegen die Meldung "Ungültige Modell-URL".
Ich hätte jedoch das Anzeigen der Modell-Details erwartet.

**Comment by olivergrimm** [comment]
> Beim Aufrufen der Detail-Info (Klick auf den Modell-Namen) erscheint hingegen die Meldung "Ungültige Modell-URL".
> Ich hätte jedoch das Anzeigen der Modell-Details erwartet.

==> siehe #90
