### ISSUE TITLE
keine Modellvorschau

### ISSUE THREAD

**Issue by zigertiger** [GeoWerkstatt/interlis-model-browser#112]
(A) Bei (vielen? manchen?) Modellen kann keine Modellvorschau angezeigt werden (Beispiel GL_HPM_Network_Publikation_V1), jedoch funktioniert der Klick auf "Modell-URI" immer und die ILI-Datei wird im Browser angezeigt.
Bei anderen Modellen funktioniert die Vorschau (Beispiel Waldreservate_LV95_V1_1).

Grundsätzlich sollten die ILI-Dateien in der Modellvorschau immer angezeigt werden.

(B) die Modellvorschau solle auch in einer nicht-proportionalen Schrift (z.B. Courier) angezeigt werden.

**Comment by olivergrimm** [comment]
(A) Begründung siehe: #90 
(B) wird umgesetzt
