### ISSUE TITLE
Aktualisierung Modellablagen

### ISSUE THREAD

**Issue by ltzur** [GeoWerkstatt/interlis-model-browser#115]
Mit einem Leerschlag in der Suche habe ich alle 1850 Modelle erhalten. Über den Knopf Filtern kann ich nun die gefundenen Modellablagen einsehen.

Frage: Wie häufig werden die Modellablagen ausgelesen und in der Datenbank aktualisiert? Ich habe am 21.09.2022 auf Wusch der Geschäftsstelle KGK eine Änderung im ilisite.xml von models.interlis.ch vorgenommen: die URL des Repo der KGK heisst neu: models.kgk-cgc.ch (ohne .geo). Falls ein zusätzlicher Kanton ein Repository anbietet, wie rasch wird die Datei ilisite.xml, in diesem Fall von der KGK, gelesen und in der Datenbank hinzugefügt?

**Comment by ltzur** [comment]
Ich habe am 29.09.2022 im ilisite.xml von models.geo.admin.ch das Attribut Title ein wenig angepasst. Diese Anpassung ist einen Tag später in der Detailansicht korrekt sichtbar.

**Comment by olivergrimm** [comment]
> Mit einem Leerschlag in der Suche habe ich alle 1850 Modelle erhalten. Über den Knopf Filtern kann ich nun die gefundenen Modellablagen einsehen.
> 
> Frage: Wie häufig werden die Modellablagen ausgelesen und in der Datenbank aktualisiert? Ich habe am 21.09.2022 auf Wusch der Geschäftsstelle KGK eine Änderung im ilisite.xml von models.interlis.ch vorgenommen: die URL des Repo der KGK heisst neu: models.kgk-cgc.ch (ohne .geo). Falls ein zusätzlicher Kanton ein Repository anbietet, wie rasch wird die Datei ilisite.xml, in diesem Fall von der KGK, gelesen und in der Datenbank hinzugefügt?

@ltzur Der Repository-Name in http://[models.kgk-cgc.ch/ilisite.xml](http://models.kgk-cgc.ch/ilisite.xml) ist nach wie vor mit .geo angegeben. Daher wird er auch so in der Liste angezeigt.

**Comment by ltzur** [comment]
Ich habe das der KGK (Peter Staub) gemeldet, das sollte somit bald korrigiert werden.
