### ISSUE TITLE
FILTERN: Herausgeber werden nicht nachgeführt

### ISSUE THREAD

**Issue by ltzur** [GeoWerkstatt/interlis-model-browser#116]
Ich suche wiederum alle 1850 Modelle und filtere auf diejenigen der Modellablage models.geo.admin.ch. Nach Filter anwenden erhalte ich 842 Modelle. Die Spalte Herausgeber wird aber nicht aktualisiert, es werden nach wie vor alle aufgeführt, auch diejenigen der kantonalen Modelle.
Hinweis: Auch die Spalte Schemasprache wird nicht nachgeführt. Use-Case: Filterung auf alle kantonalen Repositories und Filter anwenden. Es werden 798 Modell angezeigt und alle Schemasprachen. Es gibt aber nur auf interlis.ch und models.geo.admin.ch Modelle in INTERLIS 2.2.

**Comment by olivergrimm** [comment]
Momentan zeigt der Filter keine Inhalte, wenn zB nur eine Schemasprache vorliegt (da dann ja nichts gefiltert werden kann).
Filter wird so angepasst, dass er auch bei nur einem Inhalt angezeigt wird
