### ISSUE TITLE
Bezeichnung der Modellablagen

### ISSUE THREAD

**Issue by ltzur** [GeoWerkstatt/interlis-model-browser#117]
Die Modellablagen werden ganz unterschiedlich dargestellt: beim Root-Repository steht nur interlis.ch, ich würde models.interlis.ch klar vorziehen (die Modelle sind ja nicht auf der INTERLIS-Webseite interlis.ch). Bei den Kantonen wird bei https das https angezeigt, bei denen mit http wird das http weggelassen. Vorschlag: entweder konsequent zeigen oder konsequent weglassen. Etwas weniger ausgeprägt stellt sich diese Frage auch für die Spalte Herausgeber (dort würde ich http/https wahrscheinlich eher stehen lassen).

**Comment by olivergrimm** [comment]
Nur Domainteil anzeigen
