### ISSUE TITLE
Spalte Schemasprache fehlt

### ISSUE THREAD

**Issue by ltzur** [GeoWerkstatt/interlis-model-browser#119]
Nach der Suche mit dem Stichwort Antenne erhalte ich ein Modell, bei Filtern fehlt die Spalte Schemasprache. Dasselbe passiert mit Stichwort Wildruhezonen (15 Modelle), auch hier fehlt unter Filterung die Spalte Schemasprache.

**Comment by olivergrimm** [comment]
geprüft: ilimodels-seitig werden liegt die Info vor.

**Comment by olivergrimm** [comment]
Filter anpassen, dass der Wert auch angezeigt, wenn nur eine Schemasprache voirliegt
