### ISSUE TITLE
Detailansicht

### ISSUE THREAD

**Issue by ltzur** [GeoWerkstatt/interlis-model-browser#120]
Wenn ich auf ein gefundes Modell klicke, gelange ich zur Detailansicht. Wieso sind das Datum der aktuellen Version im XML-Format, dasjenige für Zuletzt aktualisiert nicht? Z.B. swissTLMRegio_LV95_V5:
Aktuelle Version: 2022-09-07
Zuletzt aktualisiert: 27.9.2022
Soweit ich verstanden habe, kommt das zweite Datum ebenfalls aus ilimodels.xml (publishingDate) und ist somit auch im XML-Format. Sollte das nicht möglich sein, schlage ich vor, dass das Datum zumindest in der Struktur DD.MM.YYYY gezeigt wird, für unser Beispiel also 27.09.2022.

**Comment by Philippluca** [comment]
Gemäss Spezifikation vom Modell [ModelMetadata](https://models.interlis.ch/core/IliRepository20.ili) ist das Feld `Version` ein Freitext. Deshalb wird hier auf eine Interprätation verzichtet.

```INTERLIS2
ModelVersion = TEXT;
...
/** Version of the model e.g. "DM01.24"
 */
Version : MANDATORY IliRepository20.ModelVersion;
```
