### ISSUE TITLE
Exakte Suchtreffer verschwinden in der Masse

### ISSUE THREAD

**Issue by Philippluca** [GeoWerkstatt/interlis-model-browser#128]
Repro: 
Suche nach "CoordSys" oder "Units"

Ist: 
Exakte Treffer verschwinden in der Masse. 
Suchtreffer können von Referenz-treffern nicht unterschieden werden.

Erwartet:
Exakte Treffer stehen in der Liste zuoberst.

**Comment by olivergrimm** [comment]
Aktuell erfolgt noch keine Gewichtung der Treffer. Das wäre etwas für einen nächsten Ausbauschritt
