### ISSUE TITLE
Suchergebnisse verschwinden unerwartet

### ISSUE THREAD

**Issue by danjov** [GeoWerkstatt/interlis-model-browser#148]
**Repro**
1. Ich suche nach `_`
2. Es werden 1810 Modelle gefunden
3. Ich lösche den Suchbegriff `_` aus dem Eingabefeld

**Erwartet**
Es werden weiterhin die Suchergebnisse mit 1810 Modellen angezeigt.

**Beobachtet**
Die Liste der Suchergebnisse wird auf einen Treffer reduziert, ohne auf _Suchen_ geklickt zu haben.

**Comment by danjov** [comment]
Das Verhalten tritt mit Version [v0.1.77](https://github.com/GeoWerkstatt/interlis-model-browser/releases/tag/v0.1.77) weiterhin auf.

**Comment by olivergrimm** [comment]
kann nicht mehr reprodziert werden
