### ISSUE TITLE
Suchresultate speziell markieren, wenn sich Treffer auf DependsOnModels bezieht

### ISSUE THREAD

**Issue by olivergrimm** [GeoWerkstatt/interlis-model-browser#54]
Eine Markierung der Suchresultate (nur in der Liste der Suchresultate) wenn sich der Treffer auf ein DependsOnModel-Eintrag bezieht.
-Symbolisierung mit einem Katalog-Icon (Buch o.ä.)
-In Priorisierung zuunterst, falls möglich

![Image](https://user-images.githubusercontent.com/3465512/187195569-da07f2a9-b19c-4b44-9ec1-a69d2feac1b1.png)

**Comment by MiraGeowerkstatt** [comment]
Die Modelle die nur über "DependsOnModels" gefunden werden, werden beim Sortieren der Resultate ans Ende gesetzen.
Ich habe den Filter ergänzt, sodass die Resultate die nur über "DependsOnModels" zustande kommen bei Bedarf ausgeblendet werden können.

Beispiel: Suche nach "Units"
