### ISSUE TITLE
übersetztes UI erscheint nicht nach Änderung der Browsersprache

### ISSUE THREAD

**Issue by olivergrimm** [GeoWerkstatt/interlis-model-browser#62]
Repro:
Edge: Umstellung der Browsersprache auf französisch (Schweiz). -> Browser-Neustart

Beobachtet:
UI des Model Browsers bleibt deutsch
(andere Nachrichtenwebsites werden nun französisch übersetzt angezeigt)

Erwartet:
UI des Model Browsers zeigt französische Texte an

**Comment by MiraGeowerkstatt** [comment]
Zusätzlich zum Neustart muss der Browsercache geleert werden.
