### ISSUE TITLE
Feedback zu Styling, URL und App-Name

### ISSUE THREAD

**Issue by olivergrimm** [GeoWerkstatt/interlis-model-browser#76]

**Comment by zigertiger** [comment]
- URL: ich finde https://ilimodels.ch gut
- App-Name: ich finde "INTERLIS Model Browser" gut. Halt englisch, dafür "Esprit Fédéral-neutral"...
- Styling: schlicht und simpel gefällt mir gut (v.a. auch im Hinblick auf die Einbindung als iFrame et.al. in Webseiten, wo der Browser dann (viel) kleiner erscheinen würde. 
- Evtl. könnte man noch klein und fein ein ILI-Logo einfügen.
- Ich finde, in einem Impressum können dann schon die Entwickler und die Sponsoren aufgeführt/genannt werden. M.E. gehörte dort auch ein Link auf das GitHub-Repository hinein.

**Comment by zigertiger** [comment]
ganz sexy wäre auch noch ein schönes Browser-Icon...

**Comment by olivergrimm** [comment]
@MiraGeowerkstatt meine Inputs fürs Impressum:

Sponsoring: KGK-CGC/swisstopo
Technische Hinweisezur Archiv-Interpretation: 

- Die Modellarchive werden gemäss den Angaben in ilisite.xml periodisch ausgelesen und für die Suche in PostgreSQL indexiert.
- Dieser Prozess läuft momentan nächtlich.
- Kann ein Archiv nicht erreicht werden, so wird es beim aktuellen Aktualisierungsprozess nicht berücksichtigt. Ausnahme: Wenn beim Aktualisierungsprozess ein Archiv, welches subsidiäre Archive enthält, nicht erreicht werden kann, so wird keine Aktualisierung sämtlicher Archive durchgeführt.
- Die Modellvorschau kann aufgrund restriktiver Cross-Domain-Policies nicht bei allen Archiven gewährleistet werden. In diesen Fällen ist der entsprechende Link zur Modelldatei zu nutzen.




-

**Comment by zigertiger** [comment]
Ich fände es gut, wenn (anstelle? oder zumindest zusätzlich) beim Sponsoring "Strategie Geoinformation Schweiz" stehen würde. Daraus wird die Entwicklung finanziert.
