### ISSUE TITLE
Suche teils Case sensitiv

### ISSUE THREAD

**Issue by romefi** [GeoWerkstatt/interlis-model-browser#78]
Wenn ich nach "kanton schaffhausen" suche, finde ich keine Resultate: https://ilimodels.ch/?query=kanton+schaffhausen

Wenn ich nach "Kanton Schaffhausen" suche, werden die Resultate angegeben: https://ilimodels.ch/?query=Kanton+Schaffhausen

Als Nutzender würde ich erwarten, dass die Gross/Kleinschreibung keine Rolle spielt.

**Comment by olivergrimm** [comment]
we are going to extend the case insensitivity to all search criteria.
