### ISSUE TITLE
Kataloge werden teils nicht angezeigt

### ISSUE THREAD

**Issue by romefi** [GeoWerkstatt/interlis-model-browser#82]
Für das Modell KbS_V1_5 wird der Katalog nicht angezeigt: https://ilimodels.ch/detail/b9fddd8462048e0be5fa53a0f039d376/KbS_V1_5. Auf http://models.geo.admin.ch/ilidata.xml ist der Katalog aber aufgelistet.

**Comment by olivergrimm** [comment]
Ich sehe in diesem Beispiel den Bezug von Modell zu Katalog "nur" über das Metattribut
`  !!@ limitedTo = "ch.admin.bafu.kbs_codetexte_V1_5"`

Die Einträge in ilimodels sowie ilidata für dieses Modell reichen m.E. nicht aus damit der Crawler momentan eine Katalog-Zugehörigkeit erkennt. Wir schauen dies aber nochmals genauer an.

**Comment by olivergrimm** [comment]
siehe auch #https://github.com/claeis/ilivalidator/issues/71

**Comment by olivergrimm** [comment]
wurde mit #123 gefixt.
