### ISSUE TITLE
Add hyperlink to referenced models

### ISSUE THREAD

**Issue by p1d1d1** [GeoWerkstatt/interlis-model-browser#83]
I'd add an hyperlink to referenced models. E.g. for this entry https://ilimodels.ch/detail/c5adc4042909326c16014763d30cc00c/Alpenkonvention_V1_1 I'd let "GeometryCHLV95_V1" point to https://ilimodels.ch/detail/c407a562e1e4ecbf4669228ffaa3e050/GeometryCHLV95_V1

**Comment by edigonzales** [comment]
@p1d1d1 What will happen if there are two models with the same name? Since they are not really imported "fully qualified".

**Comment by p1d1d1** [comment]
I'm refering to this:
![image](https://user-images.githubusercontent.com/1533649/188580019-c19742c6-21f7-4373-a925-cac63173753b.png)
Cannot be hyperlinked?

**Comment by edigonzales** [comment]
```
MODEL Alpenkonvention_V1_1 (de)
AT "https://models.geo.admin.ch/ARE/"
VERSION "2020-11-19"  =
  IMPORTS GeometryCHLV95_V1;
```

If I put `GeometryCHLV95_V1` in our repository. To which model do you link?

(definitely happens with the sia models ;))

**Comment by p1d1d1** [comment]
No idea! We could maybe link to something like https://ilimodels.ch/?query=GeometryCHLV95_V1 ?

**Comment by olivergrimm** [comment]
we can add the link suggested from @p1d1d1 to the items we provide under "Referenzierte Modelle". We publish a concrete URL in the case we get an address like to cataloguefiles from ilidata (f.e.: https://ilimodels.ch/detail/705b3943db8e1caab1af47c427e92547/SanierungWasserkraft_LV95_V1_1)
