### ISSUE TITLE
"Schemasprache" vs "Version"

### ISSUE THREAD

**Issue by p1d1d1** [GeoWerkstatt/interlis-model-browser#85]
"Schemasprache" is now giving the language version and this is IMHO not consistent. The "Schemasprache" is INTERLIS, while 2_3 is a version.
I'd change this to e.g.: "Schemasprache: INTERLIS 2.3"

PS: why 2_3 and not 2.3?

**Comment by olivergrimm** [comment]
We are going to change this label.
2_3 is published because it is generically interpreted out from ilimodels.xml
