### ISSUE TITLE
Localisation IT

### ISSUE THREAD

**Issue by p1d1d1** [GeoWerkstatt/interlis-model-browser#86]
Impressum --> "Impressum"
Herausgeber --> "Editore"
Modellablage --> "Archivio del modello" or simply "Archivio"
Mehr Informationen --> "Ulteriori informazioni"

PS: Please let check also FR

**Comment by MiraGeowerkstatt** [comment]
Tnanks, we've included your corrections. In these [two files](https://github.com/GeoWerkstatt/interlis-model-browser/tree/main/src/ClientApp/src/translations/it) you can see all the italian translations we're using, if you find any more mistakes.
