### ISSUE TITLE
No preview of model

### ISSUE THREAD

**Issue by edigonzales** [GeoWerkstatt/interlis-model-browser#90]
https://ilimodels.ch/?query=SZBewirtschaftungseinheit20140130

Das Datenmodell wird nicht dargestellt: "Keine Modellvorschau verfügbar".

Eventuell hat es einen Zusammenhang mit Fehlern im ilimodels.xml? 

```
Error: line 345: IliRepository09.RepositoryIndex.ModelMetadata: tid SZ_RevitalisierungGewaesser_V1_Erfassung: Attribute Title must not contain control characters
Error: line 430: IliRepository09.RepositoryIndex.ModelMetadata: tid SZ_SanierungWasserkraft_Anlage_V1_Erfassung: Attribute Title must not contain control characters
Error: line 446: IliRepository09.RepositoryIndex.ModelMetadata: tid SZ_SanierungWasserkraft_Geschiebe_V1_Erfassung: Attribute Title must not contain control characters
Error: line 463: IliRepository09.RepositoryIndex.ModelMetadata: tid SZ_SanierungWasserkraft_SchwallSunk_V1_Erfassung: Attribute Title must not contain control characters
Error: line 1142: IliRepository09.RepositoryIndex.ModelMetadata: tid SZBewirtschaftungseinheit20140130: Attribute Title must not contain control characters
Error: line 1453: IliRepository09.RepositoryIndex.ModelMetadata: tid SZ_planerischerGewaesserschutz_V2_Erfassung: Attribute Title must not contain control characters
Error: line 1784: IliRepository09.RepositoryIndex.ModelMetadata: tid SZ_Nutzungsplanung_kantonal_Siedlung_20190218: Attribute Title must not contain control characters
Error: line 1972: IliRepository09.RepositoryIndex.ModelMetadata: tid SZ_Wegrodel_V2: Attribute Title must not contain control characters
Error: line 1988: IliRepository09.RepositoryIndex.ModelMetadata: tid SZ_Wegrodel_V1: Attribute Title must not contain control characters
```

**Comment by olivergrimm** [comment]
In diesen Fällen scheint eine Cross-Origin-Policy zu greifen:

>     
       Access to fetch at 'https://models.geo.sz.ch/AFL/SZ_Bewirtschaftungseinheit_2014-01-30_ili2.ili' from origin 'https://ilimodels.ch' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by MiraGeowerkstatt** [comment]
Ja es sind CORS Probleme. 
Viele Repositories (z.B. models.geo.admin.ch) erlauben GET requests von beliebigen origins. Andere (models.geo.gl.ch, models.geo.sz.ch,www.sia.ch/405...) blockieren alle requests von externen origins. 

Wir können das Problem so nicht beheben, das können nur die Betreiber der Server.
Das beste wäre bei den entsprechenden Betreibern ein whitelisting von "ilimodels.ch" zu erwirken, damit unsere requests erlaubt werden. 

Falls erwünscht können wir inzwischen das "Modellvorschau" Feld auch komplett ausblenden, wenn die Vorschau nicht verfügbar ist.

**Comment by KunoEpper** [comment]
Fehler in im ilimodels.xml behoben
